version: '3'

includes:
  test: tasks/test.tasks.yaml

tasks:
  dev:
    desc: 'Run CLI in development mode'
    cmds:
      - bun run src/cli.ts {{.ARGS}}

  build:
    desc: 'Build standalone binary'
    cmds:
      - bun build --compile --outfile dist/kagent src/cli.ts

  clean:
    desc: 'Clean build artifacts and dependencies'
    cmds:
      - rm -rf dist node_modules coverage

  test:
    desc: 'Run all tests (unit + int)'
    cmds:
      - task: test:test

  setup:
    desc: 'Setup the repository'
    cmds: #
      - bun install
      #
      #
  lint:
    cmds:
      - pre-commit run --all

  deadcode:
    desc: 'Find code only used by tests or not used at all (requires verification)'
    cmds: #
      - bun knip --include classMembers,types
      #
