version: '3'

tasks:
  setup:
    desc: 'Install dependencies'
    cmds:
      - ./scripts/setup.sh

  dev:
    desc: 'Run CLI in development mode'
    cmds:
      - ./scripts/dev.sh {{.ARGS}}

  build:
    desc: 'Build standalone binary'
    cmds:
      - ./scripts/build.sh

  clean:
    desc: 'Clean build artifacts and dependencies'
    cmds:
      - ./scripts/clean.sh

  lint:
    desc: 'Run pre-commit hooks'
    cmds:
      - ./scripts/lint.sh

  # Alias for running all tests
  test:
    desc: 'Run all tests (unit + int)'
    cmds:
      - task: test:test

includes:
  test: tasks/test.tasks.yaml
